var HTML_SEPARATOR = '<dl>';
var HTML_URL_BEGIN = 'href=';
var HTML_URL_END = '>';
var HTML_TITLE_BEGIN = '>';
var HTML_TITLE_END = '</a>';
var HTML_NAME_BEGIN = '</a>'
var HTML_NAME_END = '</dd>';
var HTML_DATE_BEGIN = '<dt'
var HTML_DATE_END = '</dt>';
var DL_SEPARATOR = '<dl>';
var DL_URL_BEGIN = 'href=';
var DL_URL_END = '>';
var DL_OWNERID_BEGIN = 'owner_id=';
var DL_OWNERID_END = '"';
var DL_TITLE_BEGIN = '>';
var DL_TITLE_END = '</a>';
var DL_NAME_BEGIN = '</a>'
var DL_NAME_END = '<div style=';
var DL_DATE_BEGIN = '<dt'
var DL_DATE_END = '</dt>';
var FP_TOTAL_AREA_BEGIN = '<div class="logListCenter">';
var FP_TOTAL_AREA_END = '</p>';
var FP_TOTAL_BEGIN = '<strong>';
var FP_TOTAL_END = '</strong>';
var FP_AREA_BEGIN = '<ul class="logList';
var FP_AREA_END = '</ul>';
var FP_SEPARATOR = '</li>';
var FP_DATE_BEGIN = '<span class="date">';
var FP_DATE_END = '</span>';
var FP_URL_BEGIN = 'href=';
var FP_URL_END = '>';
var FP_TITLE_BEGIN = '>';
var FP_TITLE_END = '</a>';
var MS_AREA_BEGIN = '<div class="messageListBody">';
var MS_AREA_END = '</div>';
var MS_SEPARATOR = '<tr class="';
var MS_NICK_BEGIN = 'class="sender">';
var MS_NICK_END = '</td>';
var MS_DATE_BEGIN = '<td class="date">';
var MS_DATE_END = '<a';
var MS_URL_BEGIN = '"subject"><a href="';
var MS_URL_END = '">';
var MS_SUBJECT_BEGIN = '">';
var MS_SUBJECT_END = '</a>';
var MS_SENDER_BEGIN = 'class="sender">';
var MS_SENDER_END = '</td>';
var VC_AREA_BEGIN='<ul class="listArea">';
var VC_AREA_END='</ul>'
var VC_SEPARATOR = '<li class="archive">';
var VC_NICK_BEGIN = 'name="nickname" value="';
var VC_NICK_END = '"';
var VC_DATE_BEGIN = 'name="post_time" value="';
var VC_DATE_END = '"';
var VC_SUBJECT_BEGIN = '<div class="voiced">\n<p>';
var VC_SUBJECT_END = '<span>';
var VC_UID_BEGIN = 'name="member_id" value="';
var VC_UID_END = '"';
var ATOM_AREA_BEGIN = '<entry>';
var ATOM_AREA_END = '</feed>';
var ATOM_SEPARATOR = '<entry>';
var ATOM_TITLE_BEGIN = '<content>';
var ATOM_TITLE_END = '</content>';
var ATOM_URL_BEGIN = '<link rel="alternate" href="';
var ATOM_URL_END = '"';
var ATOM_DATE_BEGIN = '<updated>';
var ATOM_DATE_END = '</updated>';
var PH_AREA_BEGIN = '<!--[NewFriendPhoto]-->';
var PH_AREA_END = '<!--/[NewFriendPhoto]-->';
var PH_SEPARATOR = '<!-- [photo item] -->';
var PH_URL_BEGIN = '<a class="photo" href="';
var PH_URL_END = '">';
var PH_TITLE_BEGIN = '">';
var PH_TITLE_END = '</a>';
var PH_NICK_BEGIN = '（';
var PH_NICK_END = '）';
var PH_DATE_BEGIN = '<p class="date">';
var PH_DATE_END = '</p>';
var CK_AREA_BEGIN = '<div class="pageNavigation01">';
var CK_AREA_END = '<!--checkList-->';
var CK_SEPARATOR = '<li class="listItem';
var CK_URL_BEGIN = '<a href="view_check.pl?post_time=';
var CK_URL_END = '">';
var CK_TITLE_BEGIN = '<a target="';
var CK_TITLE_END = '</a>';
var CK_TITLE_ALT_BEGIN = '">';
var CK_TITLE_ALT_END = '</a>';
var CK_NICK_BEGIN = 'class="owner_nickname" value="';
var CK_NICK_END = '"';
var CK_DATE_BEGIN = 'class="post_time" value="';
var CK_DATE_END = '"';
